import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  mainSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'What is BSC?',
    },
    {
      type: 'doc',
      id: 'status',
      label: 'Implementation Status',
    },
    {
      type: 'category',
      label: 'Getting Started',
      collapsible: true,
      collapsed: false,
      link: { type: 'generated-index', title: 'Getting Started' },
      items: [
        'getting-started/prototype',
        'getting-started/full-stack',
        'getting-started/dev-setup',
        'getting-started/configuration',
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      collapsible: true,
      collapsed: false,
      items: [
        'concepts/overview',
        'concepts/identity-model',
        'concepts/anomaly-detection',
        'concepts/zkp',
        'concepts/roles-permissions',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      collapsible: true,
      collapsed: true,
      items: [
        'architecture/system-overview',
        'architecture/fabric-network',
        'architecture/api-gateway',
        'architecture/data-layer',
        {
          type: 'category',
          label: 'Chaincodes',
          collapsible: true,
          collapsed: false,
          items: [
            'architecture/chaincodes/anomaly',
            'architecture/chaincodes/property',
            'architecture/chaincodes/access',
            'architecture/chaincodes/zkp',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsible: true,
      collapsed: true,
      items: [
        'guides/run-prototype',
        'guides/seed-data',
        'guides/running-tests',
        'guides/deploy-chaincode',
        'guides/environment-vars',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      collapsible: true,
      collapsed: true,
      link: { type: 'doc', id: 'api-reference/introduction' },
      items: [{ type: 'autogenerated', dirName: 'api-reference' }],
    },
    {
      type: 'category',
      label: 'Adapt BSC',
      collapsible: true,
      collapsed: true,
      items: ['adaptation/index'],
    },
    {
      type: 'category',
      label: 'Whitepaper',
      collapsible: true,
      collapsed: true,
      items: ['whitepaper/index'],
    },
    {
      type: 'category',
      label: 'Community',
      collapsible: true,
      collapsed: true,
      items: [
        'contributing/index',
        'contributing/roadmap',
        'contributing/security',
      ],
    },
  ],
};

export default sidebars;
